### ISSUE TITLE
Restart in Debug Mode causes exception

### ISSUE THREAD

**Issue by billsaysthis** [Maluen/Backbone-Debugger#13]
After installing this extension and opening the Web Inspector to the Backbone panel I see a link labelled Restart app in debug mode. Clicking the link reloads the current page, which crashes trying to run main.js, on the second line in the following code fragment, reporting an error that domReady is an object:

````
require(["domReady"], function(domReady) {
  domReady(function () {
  ...
```

**Comment by Maluen** [comment]
This has been probably fixed by https://github.com/Maluen/Backbone-Debugger/commit/73a1f21b7fe55babca60faa59b2ac6dfec89452e

Please reopen if you still encounter it.
