### ISSUE TITLE
0.2.5 Loading

### ISSUE THREAD

**Issue by brock** [Maluen/Backbone-Debugger#23]
I haven't been able to use this extension since the upgrade to 0.2.5. The application I'm using has a lot of models and views, and with the extension enabled it slows the application to a crawl. Is there a way I can diagnose this a bit more or get error logs from the extension so I can hopefully provide something more helpful for you?

**Comment by Maluen** [comment]
Implemented a lazy collection reading mechanism which should improve a lot performance in debugging medium to big applications.

Reserving more work to separate issues.
