### ISSUE TITLE
Loader.js file has a console warning

### ISSUE THREAD

**Issue by specialorange** [Maluen/Backbone-Debugger#35]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

Line 11 (last line here) in loader.js
    //@ sourceURL=chrome-extension://bhljhndlimiafopmmhjlgfpnnchjjbhd/js/backboneAgent/loader.js
    // retrieve the extension url from the data passed in the inject process
    var extensionUrl = injectionData["extensionUrl"];
    
    // Configuration
    var basePath = extensionUrl+"js/backboneAgent/";
    
    var load = function(modulePath) {
        var xmlhttp = new XMLHttpRequest();
        var sourceUrl = basePath+modulePath+".js";
        xmlhttp.open("GET", sourceUrl, false); // synchronous

**Comment by Maluen** [comment]
@specialorange thanks for the report.

Loader.js is part of the old backbone agent architecture, you won't find it in the current master (it has been deleted).

This warning will disappear in the next release that (hopefully) will be out soon.
