### ISSUE TITLE
Difficulty loading iframes with 0.3.0 release

### ISSUE THREAD

**Issue by adamsea** [Maluen/Backbone-Debugger#38]
Hello,

I was using Backbone.Debugger pretty successfully before the 0.3.0 release on an embedded widget that I'm developing using Backbone.  With 0.3.0 the iframe loads, but no longer seems to respond to postMessage events.  I am unable to give a demo page right now because this product is still in an internal beta, but I can tell you that the iframe should load the backbone application after a postMessage is sent to it from the host page.

The sequence of events is:
1) Widget script is executed in the DOM
2) An iframe is created and placed into a target container in the DOM
3) Once the iframe is loaded the script then send some parameters to the iframe, which then loads the application

Once we've released our widget I can point you to a page to debug, but I'm hoping in the meantime this can get the ball rolling on a fix.

This is a great tool btw, and I hope to start using it again soon!

Thanks,
-Eric

**Comment by Maluen** [comment]
Hi @adamsea 

The issue you are experiencing could be due to the fact that we're injecting the backbone agent in all the frames right now, but hard to tell without having something to work on.

Would you be able to create a minimal demo that does the same logical steps of your widget, but without disclosing widget-specific details, just logic on the way it's loaded and so on. If this is even doable, would be huge help in tracking the bug.

**Comment by adamsea** [comment]
Hi @Maluen thanks for getting back to me - I'll try to throw a demo together in the next day or two that reproduces the issue.  Honestly our product release might come first, so either way you should have something to demo by week's end =)

**Comment by Maluen** [comment]
@adamsea any news on the demo?

**Comment by adamsea** [comment]
Hi @Maluen yes I have one - apologies for the delay!  Please take a look at http://demo.blopdev.com/embed/collection/2015/05/07/embed-collection-2.html - there should be an iframe that loads below the first paragraph in this demo.  The iframe contains questions (like a survey) - the first question is "Has Seymour Hersh identifed a real conspiracy surrounding the killing of Osama bin Laden?"

The demo will work for me if I keep Backbone Debugger disabled, but the iframe won't respond to postMessage events when it is enabled.  Thanks for taking a look!

-Eric

**Comment by Maluen** [comment]
@adamsea I get a "502 Bad Gateway" error when running the iframe without Backbone Debugger, namely, when the iframe tries to embed the script.

Anyway, I'm taking a look at the iframe script and I can see it is removing the message listener the first time the callback is called, without doing any check that the received message is actually the expected one.

Backbone Debugger has to use postMessage to establish a connection between the devtools and the agent in the page, and is doing that right on page load.

Probably what happens is that your callback is being called for the Backbone Debugger message, does nothing other than unbinding the message listener, thus it won't listen to the real embed message you will send later.

Generally speaking, you should not assume you are the only one sending messages, try to unbind the listener only when you actually received the expected message:

```javascript
		// Listen for incoming requests
		window.addEventListener('message', function loadScript(ev) {

			var l, s,
				data = ev && ev.data;
			if (data) {
				// Parse message data
				try {
					data = JSON.parse(data);
				} catch(ignore) {}

				// Load the embed application
				if (data.user === 'blopboard.embed' && /^http(?:s)?\:\/\/www\.blop(?:board|dev)\.(?:com|dev)/.test(data.url)) {
					// Load the script
					s = document.createElement('script');
					s.src = data.url;
					s.type = 'text/javascript';
					document.getElementsByTagName('head')[0].appendChild(s);

					// Set the layout
					l = data.url.match(/layout=([a-z]+)/);
					l = (l && l[1]) || 'center';
					document.body.className = ['blopboard-widget', l].join(' ');

					// @Maluen: UNBIND MOVED HERE
					// Remove the onload handler
					window.removeEventListener('message', loadScript, false);
				}
			}

		}, false);
```

**Comment by adamsea** [comment]
@Maluen That might be the case, thank you for catching that.  I'll confirm and post back here my results.  The bad gateway is a rogue nginx process we need to kill ... that should be fixed momentarily and hopefully by the time you see this you can test appropriately! =)  Thank you for taking a look!

**Comment by adamsea** [comment]
@Maluen I was able to confirm that indeed was the issue, the message event was being unbound before the script loaded.  Thanks for that suggestion!  I'll close this out as well.

**Comment by Maluen** [comment]
Great!
