### ISSUE TITLE
Using RequireJS, get this error

### ISSUE THREAD

**Issue by ORESoftware** [Maluen/Backbone-Debugger#41]
Hi there:

Looking forward to using this Chrome plugin, but I am getting a simple error. Everything is fine when I load my application as normal.

But if I click "restart the application in dev mode" like so

![screenshot 2015-07-13 14 39 56](https://cloud.githubusercontent.com/assets/11139560/8661533/17e677da-296d-11e5-839e-fcfcebfe1299.png)

then get this error

![screenshot 2015-07-13 14 37 53](https://cloud.githubusercontent.com/assets/11139560/8661520/f4c58976-296c-11e5-9a0d-a1c08fcc3c4f.png)

the error says I am missing a source-map, so maybe I should create this file :) is there any information on this? thanks

**Comment by Maluen** [comment]
Seems like an incompatibility with a RequireJS module, probably in the way it's being loaded, can you share any code that reproduces the issue?

**Comment by ORESoftware** [comment]
hmmm...all I had to do was add a blank/empty source-map.js file to the static directory. it was doing a GET for that file, but that file didn't exist prior. Do you happen to know what the source-map.js file is for?

**Comment by Maluen** [comment]
Don't know, Backbone Debugger isn't using any source map, but could be a behaviour exposed by a bug, that source-map request could actually by triggered by some library you are using.

Unfortunately, without seeing some code I can't do or say much.

**Comment by ORESoftware** [comment]
well the lib is private but maybe i can figure out how to share it

**Comment by Maluen** [comment]
Yes no need to share the whole lib, just the minimal amount that reproduces the problem.

**Comment by ORESoftware** [comment]
it's OK, it seems to work if I place the source-map.js file in the desired directory. in order to reproduce the problem you'd pretty much have to have the whole project. I can send it to you as a zip file by email, but don't know how else to share it. it would be easiest just to have the whole project.

**Comment by Maluen** [comment]
I see, not the ideal situation, but we can make it work, waiting for it then

**Comment by ORESoftware** [comment]
how do I send you an email?

**Comment by ORESoftware** [comment]
nevermind, found your email on your profile, will send shortly

**Comment by Maluen** [comment]
@ORESoftware The issue has been fixed.

The arity of the AMD define function is now preserved when patching it, since RequireJS uses it for injecting dependencies (in a fairly ugly way :|)

**Comment by ORESoftware** [comment]
"arity" ?

**Comment by Maluen** [comment]
[Function.length](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Function/length)
