### ISSUE TITLE
Can I see properties on a view object?

### ISSUE THREAD

**Issue by g-patel** [Maluen/Backbone-Debugger#47]
Is there a way to be able to see the view instance's properties and their values? When I click on the `[object Object]` link, nothing happens.

![view](https://cloud.githubusercontent.com/assets/12045773/17070970/b6dcf698-5013-11e6-9059-5952aeab015e.png)

**Comment by Maluen** [comment]
>When I click on the [object Object] link, nothing happens.

The view object is logged in the console when you click on that link. Check the Console tab.

**Comment by g-patel** [comment]
@Maluen I see, that works. Thanks. I think it would be nice to list the object in the "Backbone" tab itself so we don't have to switch dev tools tab.
