### ISSUE TITLE
Uncaught TypeError: Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by antonioquepasa** [Maluen/Backbone-Debugger#49]
Since updating to Chrome 55.0.2883.95, the extension fails to load, yielding the following error:

`VM118:955 Uncaught TypeError: Failed to execute 'postMessage' on 'Window': The 3rd argument is neither an array, nor does it have indexed properties.
    at Child.connectToExtension (<anonymous>:955:11)
    at Child.<anonymous> (<anonymous>:937:14)
    at <anonymous>:502:29`

This results in the extension never getting past the 'Waiting for Backbone" point. Anything to do with the latest fix on that piece of code?

`connectToExtension: function() {
			window.postMessage({
				target: 'page',
				timestamp: new Date().getTime(),
				name: 'connect'
			}, [this.channel.port2], '*');

			this.isConnectedWithExtension = true;
		},`

This is when it breaks down that I realize how much I use and appreciate this extension :-)

Additional info: This seems only to happen to the version distributed through the Chrome Extension store. Installing from the archive seems to be working ok.

**Comment by volleybase** [comment]
Same problem with 55.0.2883.87.

**Comment by Maluen** [comment]
This was actually fixed via https://github.com/Maluen/Backbone-Debugger/pull/48 but I forgot to push the newer version to chrome web store. Now I did, sorry!

You should get v0.3.2 in the next hours / days automatically.

In the meantime you might want to install from source by following https://github.com/Maluen/Backbone-Debugger#install-from-source

**Comment by antonioquepasa** [comment]
Confirmed, it words when installed from the source. Glad to hear it will also be updated on the store. Thanks for answering in such a quickly fashion!
